name: Deploy to GitHub Pages

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (if needed for builds)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build site (if needed)
        run: |
          # Здесь можно добавить сборку, если сайт требует компиляции (например, npm install && npm run build)

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          destination_dir: v${{ github.event.release.tag_name }}  # Публикует в подпапку по названию релиза, например v1.0
