name: Deploy to GitHub Pages

on:
  release:
    types: [published]

jobs:
 build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (if needed for builds)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./
          destination_dir: v${{ github.event.release.tag_name }}  # Публикует в подпапку по названию релиза, например v1.0
